# Generated by Django 4.2.7 on 2023-11-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobseekerupdateprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerupdateprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='jobseeker_profile_pictures/default.jpg', null=True, upload_to='jobseeker_profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='recruiterupdateprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='recruiter_profile_pictures/default.jpg', null=True, upload_to='recruiter_profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
