# Generated by Django 5.1.2 on 2025-02-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobcategory_alter_joblisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
