# Generated by Django 4.2.7 on 2024-01-24 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobseekerupdateprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.recruiterupdateprofile'),
        ),
    ]
